### ISSUE TITLE
Use Authorization header instead of deprecated query string

### ISSUE THREAD

**Issue by n1try** [Shywim/github-repo-size#18]
I just got a mail from GitHub, telling me that they have deprecated the `access_token` query string authentication. A header field should be used instead.

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

**Comment by fnkr** [comment]
Same here.

> Hi @fnkr,
> 
> On February 3rd, 2020 at 22:58 (UTC) your personal access token ([access token name]) using [user agent] was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> `https://api.github.com/repositories/[repository id]`
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
> 
> Thanks,
> The GitHub Team
