### ISSUE TITLE
Does not work on the new github repo page design.

### ISSUE THREAD

**Issue by snehitsah** [Shywim/github-repo-size#22]
Title says it all. Github released a new repository page design, which is currently opt-in. On the new design, the plugin doesn't work, i.e. the repo size isn't shown.

![image](https://user-images.githubusercontent.com/48585950/83973394-bbdc6280-a903-11ea-879b-d8c77937e607.png)

A temporary fix is to switch back to the old design. However, the old design might be eventually removed.

**Comment by Shywim** [comment]
Finally got the access to the new design on my account.

New release is up on [AMO](https://addons.mozilla.org/en-US/firefox/addon/github-repo-size/versions/)!

Thanks for the notice :)
