### ISSUE TITLE
It does not work on private repos

### ISSUE THREAD

**Issue by alexanderadam** [Shywim/github-repo-size#8]
Thank you very much for this gem! I love it!

However, it doesn't work on private repos for me.
The addon has the repo scope and the key is submitted but GitHub still shows the token as `Never used`. I also generated a new token but it still doesn't work.
I also removed and reinstalled the addon.

Any advice?

**Comment by gnowxilef** [comment]
works fine here. did you make sure to check the "repos" checkbox when you created the token?
